-- Preserve every CRM record while consolidating the legacy 15-stage workflow.
ALTER TYPE "CrmPipelineStage" RENAME TO "CrmPipelineStage_old";

CREATE TYPE "CrmPipelineStage" AS ENUM (
  'NEW_LEAD',
  'CONTACTED',
  'INTERESTED',
  'PRICE_SENT',
  'ORDER_CONFIRMED',
  'COMPLETED',
  'CANCELED'
);

ALTER TABLE "crm_customers"
  ALTER COLUMN "pipelineStage" DROP DEFAULT,
  ALTER COLUMN "pipelineStage" TYPE "CrmPipelineStage"
  USING (
    CASE "pipelineStage"::text
      WHEN 'NEW_LEAD' THEN 'NEW_LEAD'
      WHEN 'CONTACTED' THEN 'CONTACTED'
      WHEN 'NEEDS_INFORMATION' THEN 'CONTACTED'
      WHEN 'INFORMATION_SENT' THEN 'CONTACTED'
      WHEN 'INTERESTED_QUALIFIED' THEN 'INTERESTED'
      WHEN 'PROPOSAL_PRICE_SENT' THEN 'PRICE_SENT'
      WHEN 'WAITING_DECISION' THEN 'PRICE_SENT'
      WHEN 'ORDER_CONFIRMED' THEN 'ORDER_CONFIRMED'
      WHEN 'DEPOSIT_PENDING' THEN 'ORDER_CONFIRMED'
      WHEN 'DEPOSIT_CONFIRMED' THEN 'ORDER_CONFIRMED'
      WHEN 'PORTAL_INVITED' THEN 'ORDER_CONFIRMED'
      WHEN 'PROJECT_CREATED' THEN 'ORDER_CONFIRMED'
      WHEN 'DELIVERED' THEN 'COMPLETED'
      WHEN 'REPEAT_CUSTOMER' THEN 'COMPLETED'
      WHEN 'LOST_CANCELED' THEN 'CANCELED'
    END
  )::"CrmPipelineStage",
  ALTER COLUMN "pipelineStage" SET DEFAULT 'NEW_LEAD';

ALTER TABLE "opportunities"
  ALTER COLUMN "pipelineStage" DROP DEFAULT,
  ALTER COLUMN "pipelineStage" TYPE "CrmPipelineStage"
  USING (
    CASE "pipelineStage"::text
      WHEN 'NEW_LEAD' THEN 'NEW_LEAD'
      WHEN 'CONTACTED' THEN 'CONTACTED'
      WHEN 'NEEDS_INFORMATION' THEN 'CONTACTED'
      WHEN 'INFORMATION_SENT' THEN 'CONTACTED'
      WHEN 'INTERESTED_QUALIFIED' THEN 'INTERESTED'
      WHEN 'PROPOSAL_PRICE_SENT' THEN 'PRICE_SENT'
      WHEN 'WAITING_DECISION' THEN 'PRICE_SENT'
      WHEN 'ORDER_CONFIRMED' THEN 'ORDER_CONFIRMED'
      WHEN 'DEPOSIT_PENDING' THEN 'ORDER_CONFIRMED'
      WHEN 'DEPOSIT_CONFIRMED' THEN 'ORDER_CONFIRMED'
      WHEN 'PORTAL_INVITED' THEN 'ORDER_CONFIRMED'
      WHEN 'PROJECT_CREATED' THEN 'ORDER_CONFIRMED'
      WHEN 'DELIVERED' THEN 'COMPLETED'
      WHEN 'REPEAT_CUSTOMER' THEN 'COMPLETED'
      WHEN 'LOST_CANCELED' THEN 'CANCELED'
    END
  )::"CrmPipelineStage",
  ALTER COLUMN "pipelineStage" SET DEFAULT 'NEW_LEAD';

DROP TYPE "CrmPipelineStage_old";

-- CRM activity was a standalone feature; audit_logs remains the system audit trail.
DROP TABLE IF EXISTS "crm_activities";
DROP TYPE IF EXISTS "ActivityType";
