export type CrmSalesLocale = "fa" | "ps" | "en";

const CRM_SALES_COPY = {
  fa: {
    pageTitle: "CRM و فروش",
    pageSubtitle: "سرنخ‌ها، مشتریان و وضعیت چرخه فروش",
    newLead: "سرنخ جدید",
    transferToCustomers: "ارسال به مدیریت مشتریان",
    transferring: "در حال انتقال...",
    transferConfirmTitle: "انتقال مشتری به مدیریت مشتریان",
    transferConfirmBody:
      "آیا مطمئن هستید که مشتری انتخاب‌شده به صفحه مدیریت مشتریان منتقل شود؟",
    transferConfirmHint1: "پس از انتقال موفق، مشتری در مدیریت مشتریان ظاهر می‌شود.",
    transferConfirmHint2: "مشتری در CRM و فروش باقی می‌ماند و تاریخچه کامل قیف فروش حفظ می‌شود.",
    transferConfirmHint3: "سابقه CRM، فعالیت‌ها، فاکتورها و پرداخت‌ها بدون تغییر باقی می‌ماند.",
    cancel: "لغو",
    ok: "تأیید",
    confirmTransfer: "تأیید و ارسال",
    selectedCount: "{count} مشتری انتخاب شده",
    transferSuccess: "مشتری با موفقیت به مدیریت مشتریان منتقل شد.",
    transferSuccessMany: "{count} مشتری با موفقیت به مدیریت مشتریان منتقل شدند.",
    transferAlready: "{count} مشتری قبلاً منتقل شده بود.",
    transferSkipped: "{count} مشتری قابل انتقال نبود.",
    transferFailed: "انتقال مشتری انجام نشد. لطفاً دوباره تلاش کنید.",
    transferNoneSelected: "لطفاً حداقل یک مشتری را انتخاب کنید.",
    transferDisabledDelivered: "این مشتری قبلاً تحویل شده است",
    transferDisabledLost: "این مشتری لغو شده است",
    transferDisabledAlready: "این مشتری قبلاً به مدیریت مشتریان منتقل شده است",
    managementSentBadge: "در مدیریت مشتریان",
    transferAlreadySent: "منتقل‌شده",
    statusColumn: "وضعیت",
    statusLabel: "وضعیت مشتری",
    statusSaving: "در حال ذخیره...",
    statusUpdated: "وضعیت مشتری به‌روزرسانی شد.",
    statusUpdateFailed: "ذخیره وضعیت ناموفق بود.",
    selectAll: "انتخاب همه",
    selectRow: "انتخاب مشتری",
    clearSelection: "پاک کردن انتخاب",
    customerId: "شناسه مشتری",
    customer: "مشتری",
    contact: "تماس",
    category: "دسته",
    categoryGhost: "سرنخ‌های روح",
    categoryInterested: "سرنخ‌های علاقمند",
    categoryFollowUp: "سرنخ‌های قابل پیگیری",
    categoryOurCustomers: "مشتریان ما",
    categoryFilterAll: "همه دسته‌ها",
    source: "منبع ورود",
    salesOwner: "مسئول فروش",
    lastContact: "آخرین تماس",
    actions: "عملیات",
    createInvoice: "ایجاد انوایس",
    invoiceTitle: "ایجاد انوایس",
    invoiceCustomerId: "آی دی مشتری",
    invoiceCustomerName: "نام مشتری",
    invoiceCompanyName: "نام شرکت",
    invoiceVideoCount: "تعداد ویدیو",
    invoiceTotalAmount: "مبلغ کل",
    invoicePaidAmount: "مبلغ پرداخت‌شده",
    invoiceRemaining: "باقیمانده",
    invoicePaymentMethod: "روش پرداخت",
    invoicePaymentDetails: "جزئیات روش پرداخت",
    invoiceHesabPayAccount: "شماره حساب پی",
    invoiceOfficeAddress: "آدرس دفتر",
    invoiceResponsiblePhone: "شماره تماس مسئول دفتر",
    invoiceBankCard: "شماره کارت بانکی",
    invoiceNotes: "یادداشت",
    invoiceNotesHint: "توضیحات یا دستورالعمل ویژه مربوط به این فاکتور",
    invoiceSubmit: "صدور انوایس",
    invoiceCreating: "در حال صدور...",
    invoiceCreated: "انوایس با موفقیت ایجاد شد.",
    invoiceCustomerTransferred:
      "انوایس صادر شد و مشتری به‌صورت خودکار به مدیریت مشتریان منتقل شد.",
    invoiceCreateFailed: "صدور انوایس ناموفق بود.",
    invoiceClosed: "برای سرنخ لغوشده نمی‌توان انوایس صادر کرد.",
    invoicePaidExceedsTotal: "مبلغ پرداخت‌شده نمی‌تواند از مبلغ کل بیشتر باشد.",
    invoiceVideoRequired: "تعداد ویدیو را وارد کنید.",
    invoiceTotalRequired: "مبلغ کل را وارد کنید.",
    invoiceMethodRequired: "روش پرداخت را انتخاب کنید.",
    invoiceHesabRequired: "شماره حساب پی الزامی است.",
    invoiceAddressRequired: "آدرس دفتر الزامی است.",
    invoicePhoneRequired: "شماره تماس مسئول دفتر الزامی است.",
    invoiceCardRequired: "شماره کارت بانکی الزامی است.",
    invoiceCustomerSection: "اطلاعات مشتری",
    invoiceServiceSection: "جزئیات خدمات",
    invoiceFinanceSection: "خلاصه مالی",
    invoicePaymentSection: "روش و جزئیات پرداخت",
    invoiceNotesSection: "یادداشت فاکتور",
    invoiceRequiredMark: "الزامی",
    viewInvoices: "مشاهده انوایس",
    invoiceSectionTitle: "انوایس‌ها",
    invoiceEmpty: "انوایسی برای این مشتری ثبت نشده است.",
    invoiceEmptyHint:
      "انوایس‌های صادرشده از CRM و فروش اینجا ذخیره می‌شوند و مستقل از جزئیات قرارداد هستند.",
    invoiceDetails: "جزئیات انوایس",
    invoiceNumber: "شماره انوایس",
    invoiceStatus: "وضعیت",
    invoiceIssuedAt: "تاریخ صدور",
    invoiceBackToList: "بازگشت به فهرست",
    invoiceLoadFailed: "بارگذاری انوایس ناموفق بود.",
    invoiceClose: "بستن",
    invoiceViewReceipt: "مشاهده رسید",
    invoiceStatusDraft: "پیش‌نویس",
    invoiceStatusIssued: "صادر شده",
    invoiceStatusPartial: "پرداخت جزئی",
    invoiceStatusPaid: "پرداخت شده",
    invoiceStatusOverdue: "سررسید گذشته",
    invoiceStatusCanceled: "لغو شده",
    invoiceItems: "اقلام فاکتور",
    invoiceQuantity: "تعداد",
    invoiceUnitPrice: "قیمت واحد",
    invoiceLineAmount: "مبلغ",
    invoiceDescription: "شرح",
    invoiceDocumentTitle: "فاکتور",
    invoiceOfficial: "فاکتور",
    invoiceViewDocument: "مشاهده فاکتور",
    invoicePrint: "چاپ",
    invoiceDownloadPdf: "دانلود PDF",
    invoiceSendCustomer: "ارسال به مشتری",
    invoiceShare: "اشتراک‌گذاری",
    invoiceFrom: "از",
    invoiceBillTo: "صورتحساب برای",
    invoiceGrandTotal: "مبلغ مجموعی",
    invoicePaid: "مبلغ پرداخت شده",
    invoiceRemainingAmount: "مبلغ باقی‌مانده",
    invoiceRecordedBy: "ثبت‌کننده",
    invoiceThankYou: "از همکاری شما سپاسگزاریم",
    invoicePdfDownloaded: "PDF فاکتور دانلود شد.",
    invoicePrintFailed: "چاپ فاکتور ناموفق بود.",
    invoicePdfFailed: "دانلود PDF ناموفق بود.",
    invoiceSendFailed: "شماره واتساپ مشتری برای ارسال فاکتور موجود نیست.",
    invoiceShareCopied: "متن فاکتور کپی شد.",
    invoiceShareFailed: "اشتراک‌گذاری ناموفق بود.",
    invoiceShareTitle: "فاکتور {number}",
    invoiceSendMessage:
      "سلام {name}،\nفاکتور شماره {number} به مبلغ {total} صادر شد.\nمبلغ پرداخت‌شده: {paid}\nباقیمانده: {remaining}\n— APEX SMART MARKETING",
    statusAutomaticHint: "این وضعیت به‌صورت خودکار با رویدادهای سیستم به‌روز می‌شود.",
    statusDeliveredHint:
      "پروژه تحویل شده است. برای سفارش جدید، وضعیت «مشتری تکراری» را فعال کنید.",
    statusAutoTag: "خودکار",
    statusManualTag: "دستی",
    repeatCustomerTitle: "مشتری تکراری",
    repeatCustomerConfirm:
      "این مشتری قبلاً در سیستم ثبت شده است. آیا می‌خواهید برای این مشتری یک پروژه/سفارش جدید ایجاد کنید؟",
    repeatCustomerCreating: "در حال ایجاد سفارش...",
    repeatCustomerSuccess:
      "سفارش جدید ایجاد شد. اطلاعات قرارداد و پرداخت خالی است و حساب پورتال قبلی حفظ شد.",
    methodHesabPay: "حساب پی",
    methodCash: "نقدی / حضوری",
    methodBankTransfer: "انتقال بانکی",
  },
  ps: {
    pageTitle: "CRM او پلور",
    pageSubtitle: "سرنخونه، پیرودونکي او د پلور بهیر",
    newLead: "نوی سرنخ",
    transferToCustomers: "د پیرودونکو مدیریت ته واستوئ",
    transferring: "لیږدول کېږي...",
    transferConfirmTitle: "پیرودونکی د پیرودونکو مدیریت ته ولیږدول شي",
    transferConfirmBody:
      "ایا ډاډه یاست چې ټاکل شوی پیرودونکی د پیرودونکو مدیریت پاڼې ته ولیږدول شي؟",
    transferConfirmHint1: "له بریالي لیږد وروسته به پیرودونکی په مدیریت کې ښکاره شي.",
    transferConfirmHint2: "پیرودونکی به په CRM و فروش کې پاتې شي او بشپړ تاریخچه به وساتل شي.",
    transferConfirmHint3: "د CRM تاریخچه، فعالیتونه، فاکتورونه او پرداختونه خوندي پاتېږي.",
    cancel: "لغوه",
    ok: "تایید",
    confirmTransfer: "تایید او استول",
    selectedCount: "{count} پیرودونکي ټاکل شوي",
    transferSuccess: "پیرودونکی په بریالیتوب سره مدیریت ته ولیږدول شو.",
    transferSuccessMany: "{count} پیرودونکي په بریالیتوب سره ولیږدول شول.",
    transferAlready: "{count} پیرودونکی له مخکې لیږدول شوی و.",
    transferSkipped: "{count} پیرودونکی د لیږد وړ نه و.",
    transferFailed: "لیږد ترسره نه شو. مهرباني وکړئ بیا هڅه وکړئ.",
    transferNoneSelected: "لږ تر لږه یو پیرودونکی وټاکئ.",
    transferDisabledDelivered: "دا پیرودونکی له مخکې سپارل شوی دی",
    transferDisabledLost: "دا پیرودونکی لغوه شوی دی",
    transferDisabledAlready: "دا پیرودونکی له مخکې مدیریت ته لیږدول شوی دی",
    managementSentBadge: "په مدیریت کې",
    transferAlreadySent: "لیږدول شوی",
    statusColumn: "حالت",
    statusLabel: "د پیرودونکي حالت",
    statusSaving: "ساتل کېږي...",
    statusUpdated: "حالت تازه شو.",
    statusUpdateFailed: "د حالت ساتل ناکام شول.",
    selectAll: "ټول وټاکئ",
    selectRow: "پیرودونکی وټاکئ",
    clearSelection: "ټاکنه پاک کړئ",
    customerId: "د پیرودونکي پېژند",
    customer: "پیرودونکی",
    contact: "اړیکه",
    category: "کټګوري",
    categoryGhost: "د روح سرنخونه",
    categoryInterested: "علاقمند سرنخونه",
    categoryFollowUp: "د تعقیب وړ سرنخونه",
    categoryOurCustomers: "زموږ پیرودونکي",
    categoryFilterAll: "ټولې کټګورۍ",
    source: "سرچینه",
    salesOwner: "د پلور مسؤل",
    lastContact: "وروستۍ اړیکه",
    actions: "چلندونه",
    createInvoice: "انوایس جوړول",
    invoiceTitle: "انوایس جوړول",
    invoiceCustomerId: "د پیرودونکي آی ډي",
    invoiceCustomerName: "د پیرودونکي نوم",
    invoiceCompanyName: "د شرکت نوم",
    invoiceVideoCount: "د ویډیوګانو شمېر",
    invoiceTotalAmount: "ټول مبلغ",
    invoicePaidAmount: "ورکړل شوی مبلغ",
    invoiceRemaining: "پاتې مبلغ",
    invoicePaymentMethod: "د ورکړې لاره",
    invoicePaymentDetails: "د ورکړې جزئیات",
    invoiceHesabPayAccount: "د حساب پی شمېره",
    invoiceOfficeAddress: "د دفتر پته",
    invoiceResponsiblePhone: "د دفتر مسئول تلیفون",
    invoiceBankCard: "د بانک کارت شمېره",
    invoiceNotes: "یادښت",
    invoiceNotesHint: "د دې فاکتور اضافي توضیحات",
    invoiceSubmit: "انوایس صادرول",
    invoiceCreating: "صادریږي...",
    invoiceCreated: "انوایس په بریالیتوب سره جوړ شو.",
    invoiceCustomerTransferred:
      "انوایس صادر شو او پیرودونکی په اوتومات ډول مدیریت ته ولیږدول شو.",
    invoiceCreateFailed: "د انوایس جوړول ناکام شول.",
    invoiceClosed: "د لغوه شوي سرنخ لپاره انوایس نشی صادرېدای.",
    invoicePaidExceedsTotal: "ورکړل شوی مبلغ له ټول مبلغ څخه زیات کېدای نشي.",
    invoiceVideoRequired: "د ویډیوګانو شمېر ولیکئ.",
    invoiceTotalRequired: "ټول مبلغ ولیکئ.",
    invoiceMethodRequired: "د ورکړې لاره وټاکئ.",
    invoiceHesabRequired: "د حساب پی شمېره اړینه ده.",
    invoiceAddressRequired: "د دفتر پته اړینه ده.",
    invoicePhoneRequired: "د دفتر مسئول تلیفون اړین دی.",
    invoiceCardRequired: "د بانک کارت شمېره اړینه ده.",
    invoiceCustomerSection: "د پیرودونکي معلومات",
    invoiceServiceSection: "د خدماتو جزئیات",
    invoiceFinanceSection: "مالي لنډیز",
    invoicePaymentSection: "د ورکړې لاره او جزئیات",
    invoiceNotesSection: "د فاکتور یادښت",
    invoiceRequiredMark: "اړین",
    viewInvoices: "انوایس کتل",
    invoiceSectionTitle: "انوایسونه",
    invoiceEmpty: "د دې پیرودونکي لپاره انوایس نه دی ثبت شوی.",
    invoiceEmptyHint:
      "د CRM او پلور څخه صادر شوي انوایسونه دلته ساتل کېږي او له قرارداد څخه جلا دي.",
    invoiceDetails: "د انوایس جزئیات",
    invoiceNumber: "د انوایس شمېره",
    invoiceStatus: "حالت",
    invoiceIssuedAt: "د صدور نېټه",
    invoiceBackToList: "بیرته لېست ته",
    invoiceLoadFailed: "د انوایس بارول ناکام شول.",
    invoiceClose: "تړل",
    invoiceViewReceipt: "رسید کتل",
    invoiceStatusDraft: "مسوده",
    invoiceStatusIssued: "صادر شوی",
    invoiceStatusPartial: "برخه ورکړه",
    invoiceStatusPaid: "ورکړل شوی",
    invoiceStatusOverdue: "له مودې تېر",
    invoiceStatusCanceled: "لغوه شوی",
    invoiceItems: "د فاکتور توکي",
    invoiceQuantity: "شمېر",
    invoiceUnitPrice: "واحد قیمت",
    invoiceLineAmount: "مبلغ",
    invoiceDescription: "شرح",
    invoiceDocumentTitle: "انوایس",
    invoiceOfficial: "انوایس",
    invoiceViewDocument: "انوایس کتل",
    invoicePrint: "چاپ",
    invoiceDownloadPdf: "PDF ښکته کول",
    invoiceSendCustomer: "پیرودونکي ته استول",
    invoiceShare: "شریکول",
    invoiceFrom: "له",
    invoiceBillTo: "بل د",
    invoiceGrandTotal: "ټول مبلغ",
    invoicePaid: "ورکړل شوی مبلغ",
    invoiceRemainingAmount: "پاتې مبلغ",
    invoiceRecordedBy: "ثبت کوونکی",
    invoiceThankYou: "ستاسو د همکارۍ مننه",
    invoicePdfDownloaded: "د انوایس PDF ښکته شو.",
    invoicePrintFailed: "د انوایس چاپ ناکام شو.",
    invoicePdfFailed: "د PDF ښکته کول ناکام شول.",
    invoiceSendFailed: "د پیرودونکي واتساپ د انوایس استولو لپاره نشته.",
    invoiceShareCopied: "د انوایس متن کاپي شو.",
    invoiceShareFailed: "شریکول ناکام شول.",
    invoiceShareTitle: "انوایس {number}",
    invoiceSendMessage:
      "سلام {name}،\nانوایس شمېره {number} په مبلغ {total} صادر شو.\nورکړل شوی: {paid}\nپاتې: {remaining}\n— APEX SMART MARKETING",
    statusAutomaticHint: "دا حالت په اوتومات ډول د سیسټم پیښو سره تازه کېږي.",
    statusDeliveredHint:
      "پروژه سپارل شوې ده. د نوي سفارش لپاره «تکراري پیرودونکی» فعال کړئ.",
    statusAutoTag: "اتومات",
    statusManualTag: "لاسي",
    repeatCustomerTitle: "تکراري پیرودونکی",
    repeatCustomerConfirm:
      "دا پیرودونکی له مخکې په سیسټم کې ثبت شوی دی. ایا غواړئ د دې پیرودونکي لپاره نوی پروژه/سفارش جوړ کړئ؟",
    repeatCustomerCreating: "سفارش جوړېږي...",
    repeatCustomerSuccess:
      "نوی سفارش جوړ شو. د قرارداد او تادیې معلومات خالي دي او پخوانی پورټال حساب خوندي پاتې شو.",
    methodHesabPay: "حساب پی",
    methodCash: "نغدي / حضوري",
    methodBankTransfer: "بانکي لېږد",
  },
  en: {
    pageTitle: "CRM & Sales",
    pageSubtitle: "Leads, customers, and the sales cycle",
    newLead: "New lead",
    transferToCustomers: "Send to Customer Management",
    transferring: "Transferring...",
    transferConfirmTitle: "Transfer customer to Customer Management",
    transferConfirmBody:
      "Are you sure you want to transfer the selected customer to Customer Management?",
    transferConfirmHint1: "After a successful transfer, the customer will appear in Customer Management.",
    transferConfirmHint2: "The customer remains visible in CRM & Sales with full pipeline history preserved.",
    transferConfirmHint3: "CRM history, activity, invoices, and payments are kept intact.",
    cancel: "Cancel",
    ok: "OK",
    confirmTransfer: "Confirm and send",
    selectedCount: "{count} customers selected",
    transferSuccess: "Customer transferred to Customer Management.",
    transferSuccessMany: "{count} customers were transferred to Customer Management.",
    transferAlready: "{count} customers were already transferred.",
    transferSkipped: "{count} customers could not be transferred.",
    transferFailed: "The transfer could not be completed. Please try again.",
    transferNoneSelected: "Please select at least one customer.",
    transferDisabledDelivered: "This customer has already been delivered",
    transferDisabledLost: "This customer has been canceled",
    transferDisabledAlready: "This customer was already moved to Customer Management",
    managementSentBadge: "In Customer Management",
    transferAlreadySent: "Transferred",
    statusColumn: "Status",
    statusLabel: "Customer status",
    statusSaving: "Saving...",
    statusUpdated: "Customer status updated.",
    statusUpdateFailed: "Could not save the status.",
    selectAll: "Select all",
    selectRow: "Select customer",
    clearSelection: "Clear selection",
    customerId: "Customer ID",
    customer: "Customer",
    contact: "Contact",
    category: "Category",
    categoryGhost: "Ghost leads",
    categoryInterested: "Interested leads",
    categoryFollowUp: "Follow-up leads",
    categoryOurCustomers: "Our customers",
    categoryFilterAll: "All categories",
    source: "Source",
    salesOwner: "Sales owner",
    lastContact: "Last contact",
    actions: "Actions",
    createInvoice: "Create Invoice",
    invoiceTitle: "Create Invoice",
    invoiceCustomerId: "Customer ID",
    invoiceCustomerName: "Customer name",
    invoiceCompanyName: "Company name",
    invoiceVideoCount: "Number of videos",
    invoiceTotalAmount: "Total amount",
    invoicePaidAmount: "Amount paid",
    invoiceRemaining: "Remaining balance",
    invoicePaymentMethod: "Payment method",
    invoicePaymentDetails: "Payment method details",
    invoiceHesabPayAccount: "Hesab Pay account number",
    invoiceOfficeAddress: "Office address",
    invoiceResponsiblePhone: "Office representative phone",
    invoiceBankCard: "Bank card number",
    invoiceNotes: "Notes",
    invoiceNotesHint: "Additional information or special instructions for this invoice",
    invoiceSubmit: "Issue invoice",
    invoiceCreating: "Issuing...",
    invoiceCreated: "Invoice created successfully.",
    invoiceCustomerTransferred:
      "Invoice issued and the customer was automatically moved to Customer Management.",
    invoiceCreateFailed: "Could not create the invoice.",
    invoiceClosed: "An invoice cannot be issued for a lost or canceled lead.",
    invoicePaidExceedsTotal: "Amount paid cannot exceed the total amount.",
    invoiceVideoRequired: "Enter the number of videos.",
    invoiceTotalRequired: "Enter the total amount.",
    invoiceMethodRequired: "Select a payment method.",
    invoiceHesabRequired: "Hesab Pay account number is required.",
    invoiceAddressRequired: "Office address is required.",
    invoicePhoneRequired: "Office representative phone is required.",
    invoiceCardRequired: "Bank card number is required.",
    invoiceCustomerSection: "Customer details",
    invoiceServiceSection: "Service details",
    invoiceFinanceSection: "Financial summary",
    invoicePaymentSection: "Payment method and details",
    invoiceNotesSection: "Invoice notes",
    invoiceRequiredMark: "Required",
    viewInvoices: "View invoices",
    invoiceSectionTitle: "Invoices",
    invoiceEmpty: "No invoices have been recorded for this customer.",
    invoiceEmptyHint:
      "Invoices issued from CRM & Sales are stored here and stay independent of contract details.",
    invoiceDetails: "Invoice details",
    invoiceNumber: "Invoice number",
    invoiceStatus: "Status",
    invoiceIssuedAt: "Issue date",
    invoiceBackToList: "Back to list",
    invoiceLoadFailed: "Could not load the invoice.",
    invoiceClose: "Close",
    invoiceViewReceipt: "View receipt",
    invoiceStatusDraft: "Draft",
    invoiceStatusIssued: "Issued",
    invoiceStatusPartial: "Partially paid",
    invoiceStatusPaid: "Paid",
    invoiceStatusOverdue: "Overdue",
    invoiceStatusCanceled: "Canceled",
    invoiceItems: "Line items",
    invoiceQuantity: "Qty",
    invoiceUnitPrice: "Unit price",
    invoiceLineAmount: "Amount",
    invoiceDescription: "Description",
    invoiceDocumentTitle: "Invoice",
    invoiceOfficial: "Invoice",
    invoiceViewDocument: "View invoice",
    invoicePrint: "Print",
    invoiceDownloadPdf: "Download PDF",
    invoiceSendCustomer: "Send to customer",
    invoiceShare: "Share",
    invoiceFrom: "From",
    invoiceBillTo: "Bill to",
    invoiceGrandTotal: "Total amount",
    invoicePaid: "Amount paid",
    invoiceRemainingAmount: "Remaining amount",
    invoiceRecordedBy: "Recorded by",
    invoiceThankYou: "Thank you for your business",
    invoicePdfDownloaded: "Invoice PDF downloaded.",
    invoicePrintFailed: "Could not print the invoice.",
    invoicePdfFailed: "Could not download the PDF.",
    invoiceSendFailed: "This customer has no WhatsApp number for sending the invoice.",
    invoiceShareCopied: "Invoice text copied.",
    invoiceShareFailed: "Could not share the invoice.",
    invoiceShareTitle: "Invoice {number}",
    invoiceSendMessage:
      "Hello {name},\nInvoice {number} was issued for {total}.\nPaid: {paid}\nRemaining: {remaining}\n— APEX SMART MARKETING",
    statusAutomaticHint: "This status is updated automatically by system events.",
    statusDeliveredHint:
      "The project is delivered. Activate Repeat Customer to start a new project cycle.",
    statusAutoTag: "Auto",
    statusManualTag: "Manual",
    repeatCustomerTitle: "Repeat customer",
    repeatCustomerConfirm:
      "This customer is already registered in the system. Do you want to create a new project/order for this customer?",
    repeatCustomerCreating: "Creating order...",
    repeatCustomerSuccess:
      "New order created. Contract and payment fields are blank, and the existing portal account was kept.",
    methodHesabPay: "Hesab Pay",
    methodCash: "Cash / In-person",
    methodBankTransfer: "Bank transfer",
  },
} as const;

export type CrmSalesCopyKey = keyof typeof CRM_SALES_COPY.fa;

const APP_LOCALE: CrmSalesLocale = "fa";

export function crmSalesText(
  key: CrmSalesCopyKey,
  vars?: Record<string, string | number>,
): string {
  const table = CRM_SALES_COPY[APP_LOCALE] || CRM_SALES_COPY.fa;
  let text: string = table[key] || CRM_SALES_COPY.fa[key] || key;
  if (vars) {
    for (const [name, value] of Object.entries(vars)) {
      text = text.split(`{${name}}`).join(String(value));
    }
  }
  return text;
}
